name: super_memory
description: A memory training and management application.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # 基本的なユーティリティ
  intl: ^0.18.1
  path_provider: ^2.1.1
  path: ^1.8.3
  
  # データベース
  sqflite: ^2.3.0
  
  # UI関連
  cupertino_icons: ^1.0.6
  flutter_launcher_icons: ^0.13.1
  floating_search_bar: ^0.3.0

  # 状態管理
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/sprash.png
    - assets/brain.png
    - assets/background.png

flutter_icons:
  android: true 
  ios: true
  image_path: "assets/brain.png"
